In [4]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [5]:
merged = pd.read_csv("../data/processed/merged_1.csv", parse_dates=["date", "intervention_start", "intervention_end"])

In [6]:
# Sleep features

In [7]:
# --- Sleep Deficit ---
merged["avg_sleep_user"] = merged.groupby("user_id")["sleep_hours"].transform("mean")
merged["sleep_deficit"] = merged["avg_sleep_user"] - merged["sleep_hours"]

# --- Rolling Sleep Average (7-day) ---
merged["sleep_rolling_avg_7d"] = merged.groupby("user_id")["sleep_hours"].transform(lambda x: x.rolling(7, min_periods=3).mean())

# --- Sleep Variability (7-day rolling std) ---
merged["sleep_var_7d"] = merged.groupby("user_id")["sleep_hours"].transform(lambda x: x.rolling(7, min_periods=3).std())

# --- Sleep Quality Normalized ---
merged["sleep_quality_norm"] = merged["sleep_quality"] / merged["sleep_quality"].max()

In [8]:
merged

,user_id,date,week_start,workday,profession,work_mode,chronotype,age,sex,height_cm,...,cheat_meals_count_y,intervention_start,intervention_end,intervention_type,intervention_intensity,avg_sleep_user,sleep_deficit,sleep_rolling_avg_7d,sleep_var_7d,sleep_quality_norm
0,1,2024-01-01,2024-01-01,1,operations,onsite,morning,27,female,174,...,1,NaT,NaT,NaN,NaN,7.530999,0.390999,NaN,NaN,0.6
1,110,2024-01-01,2024-01-01,1,teacher,onsite,morning,40,female,165,...,1,NaT,NaT,NaN,NaN,7.480424,0.900424,NaN,NaN,0.6
2,766,2024-01-01,2024-01-01,1,operations,onsite,morning,65,female,171,...,0,NaT,NaT,NaN,NaN,7.459330,0.889330,NaN,NaN,0.6
3,767,2024-01-01,2024-01-01,1,wellness_coach,remote,evening,42,female,172,...,2,NaT,NaT,NaN,NaN,6.922503,-0.207497,NaN,NaN,0.6
4,109,2024-01-01,2024-01-01,1,teacher,onsite,intermediate,35,male,163,...,0,NaT,NaT,NaN,NaN,7.259070,-0.110930,NaN,NaN,0.7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
730995,659,2025-12-31,2025-12-29,1,manager,onsite,intermediate,41,female,160,...,0,NaT,NaT,NaN,NaN,7.224528,0.654528,6.905714,0.593573,0.6
730996,658,2025-12-31,2025-12-29,1,operations,onsite,intermediate,62,female,170,...,1,NaT,NaT,NaN,NaN,7.325896,0.195896,7.338571,0.367670,0.6
730997,657,2025-12-31,2025-12-29,1,manager,onsite,morning,34,male,182,...,2,NaT,NaT,NaN,NaN,7.400219,0.700219,7.484286,1.048028,0.6
730998,670,2025-12-31,2025-12-29,1,operations,onsite,intermediate,55,male,166,...,0,NaT,NaT,NaN,NaN,7.131464,-0.418536,6.858571,0.595215,0.6
730999,1000,2025-12-31,2025-12-29,1,manager,onsite,intermediate,58,female,168,...,1,NaT,NaT,NaN,NaN,7.281902,-0.558098,7.758571,0.543367,0.5

In [9]:
merged["sleep_quality"]

0         6
1         6
2         6
3         6
4         7
         ..
730995    6
730996    6
730997    6
730998    6
730999    5
Name: sleep_quality, Length: 731000, dtype: int64

In [13]:
# Large positive sleep_deficit suggests chronic under-sleeping.
# High sleep_var_7d suggests irregular sleep pattern → fatigue risk.

In [10]:
# Work and Productivity

In [11]:
# --- Workload Index ---
merged["workload_index"] = (
    merged["work_hours"] +
    0.5 * merged["meetings_count"] +
    0.2 * merged["emails_received"]
)

# --- Work Stress Ratio ---
merged["work_stress_ratio"] = merged["workload_index"] / (merged["stress_level"] + 1)

# --- Productivity Score ---
merged["productivity_score"] = merged["tasks_completed"] / (merged["work_hours"] + 1)

# --- Focus-to-Fatigue Ratio ---
merged["focus_fatigue_ratio"] = merged["focus_score"] / (merged["stress_level"] + 1)

In [12]:
merged

,user_id,date,week_start,workday,profession,work_mode,chronotype,age,sex,height_cm,...,intervention_intensity,avg_sleep_user,sleep_deficit,sleep_rolling_avg_7d,sleep_var_7d,sleep_quality_norm,workload_index,work_stress_ratio,productivity_score,focus_fatigue_ratio
0,1,2024-01-01,2024-01-01,1,operations,onsite,morning,27,female,174,...,NaN,7.530999,0.390999,NaN,NaN,0.6,18.69,3.738000,0.750939,1.400000
1,110,2024-01-01,2024-01-01,1,teacher,onsite,morning,40,female,165,...,NaN,7.480424,0.900424,NaN,NaN,0.6,25.72,4.286667,0.945378,1.166667
2,766,2024-01-01,2024-01-01,1,operations,onsite,morning,65,female,171,...,NaN,7.459330,0.889330,NaN,NaN,0.6,26.96,5.392000,0.982533,0.800000
3,767,2024-01-01,2024-01-01,1,wellness_coach,remote,evening,42,female,172,...,NaN,6.922503,-0.207497,NaN,NaN,0.6,29.33,5.866000,1.513241,1.200000
4,109,2024-01-01,2024-01-01,1,teacher,onsite,intermediate,35,male,163,...,NaN,7.259070,-0.110930,NaN,NaN,0.7,25.68,6.420000,0.613497,1.750000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
730995,659,2025-12-31,2025-12-29,1,manager,onsite,intermediate,41,female,160,...,NaN,7.224528,0.654528,6.905714,0.593573,0.6,25.42,6.355000,0.997506,1.000000
730996,658,2025-12-31,2025-12-29,1,operations,onsite,intermediate,62,female,170,...,NaN,7.325896,0.195896,7.338571,0.367670,0.6,23.00,3.833333,0.985915,1.166667
730997,657,2025-12-31,2025-12-29,1,manager,onsite,morning,34,male,182,...,NaN,7.400219,0.700219,7.484286,1.048028,0.6,16.19,4.047500,0.639659,0.750000
730998,670,2025-12-31,2025-12-29,1,operations,onsite,intermediate,55,male,166,...,NaN,7.131464,-0.418536,6.858571,0.595215,0.6,26.80,3.828571,0.347826,0.714286
730999,1000,2025-12-31,2025-12-29,1,manager,onsite,intermediate,58,female,168,...,NaN,7.281902,-0.558098,7.758571,0.543367,0.5,41.34,6.890000,0.281955,1.000000

In [14]:
# low focus_fatigue_ratio even with high work_hours suggests early burnout signal.

In [15]:
# Lifestyle and screen time

In [16]:
# --- Screen Stress Ratio ---
merged["screen_stress_ratio"] = merged["screen_time_hours"] / (merged["stress_level"] + 1)

# --- Outdoor Time Ratio ---
merged["outdoor_ratio"] = merged["outdoor_time_minutes"] / (merged["outdoor_time_minutes"] + merged["screen_time_hours"] + 1)

# --- Diet Quality Scaled ---
merged["diet_score_norm"] = merged["diet_quality"] / merged["diet_quality"].max()

# --- Calorie Balance ---
merged["calorie_balance"] = merged["calories_intake"] - merged.groupby("user_id")["calories_intake"].transform("mean")

In [17]:
# high outdoor ratio = positive recovery

In [18]:
# Mood and stress

In [19]:
# --- Rolling Averages ---
merged["mood_rolling_avg_7d"] = merged.groupby("user_id")["mood_score"].transform(lambda x: x.rolling(7, min_periods=3).mean())
merged["stress_rolling_avg_7d"] = merged.groupby("user_id")["stress_level"].transform(lambda x: x.rolling(7, min_periods=3).mean())

# --- Mood Volatility (std) ---
merged["mood_volatility_7d"] = merged.groupby("user_id")["mood_score"].transform(lambda x: x.rolling(7, min_periods=3).std())

# --- Stress Trend (difference between last and first 7-day window) ---
merged["stress_trend"] = merged.groupby("user_id")["stress_level"].transform(lambda x: x.diff().rolling(7, min_periods=3).mean())

In [21]:
# Health Index (core output variable for viz and LLM insights)

In [ ]:
# Normalize key features to 0–1 range
for col in ["sleep_deficit", "stress_level", "workload_index", "screen_stress_ratio"]:
    merged[f"{col}_norm"] = (merged[col] - merged[col].min()) / (merged[col].max() - merged[col].min())

# Compute the index (lower stress/deficit, higher mood/quality)
merged["health_twin_index"] = (
    0.3 * (1 - merged["sleep_deficit_norm"]) +
    0.25 * (1 - merged["stress_level_norm"]) +
    0.25 * merged["mood_score"] / merged["mood_score"].max() +
    0.2 * merged["sleep_quality_norm"]
) * 100

In [23]:
# Intervention Impact (Allows causal analysis)

In [24]:
merged["under_intervention"] = merged["intervention_type"].notna().astype(int)

# Rolling improvement in mood during interventions
merged["mood_change_during_intervention"] = merged.groupby("user_id")["mood_score"].transform(lambda x: x.diff()) * merged["under_intervention"]

# Post-intervention recovery metric
merged["stress_reduction_post_intervention"] = merged.groupby("user_id")["stress_level"].transform(lambda x: x.shift(1) - x) * merged["under_intervention"]

In [25]:
merged.shape

(731000, 85)

In [26]:
merged

,user_id,date,week_start,workday,profession,work_mode,chronotype,age,sex,height_cm,...,outdoor_ratio,diet_score_norm,calorie_balance,mood_rolling_avg_7d,stress_rolling_avg_7d,mood_volatility_7d,stress_trend,under_intervention,mood_change_during_intervention,stress_reduction_post_intervention
0,1,2024-01-01,2024-01-01,1,operations,onsite,morning,27,female,174,...,0.426569,0.4,-116.689466,NaN,NaN,NaN,NaN,0,NaN,NaN
1,110,2024-01-01,2024-01-01,1,teacher,onsite,morning,40,female,165,...,0.000000,0.9,-11.210670,NaN,NaN,NaN,NaN,0,NaN,NaN
2,766,2024-01-01,2024-01-01,1,operations,onsite,morning,65,female,171,...,0.722698,0.6,-149.300958,NaN,NaN,NaN,NaN,0,NaN,NaN
3,767,2024-01-01,2024-01-01,1,wellness_coach,remote,evening,42,female,172,...,0.000000,0.7,-413.099863,NaN,NaN,NaN,NaN,0,NaN,NaN
4,109,2024-01-01,2024-01-01,1,teacher,onsite,intermediate,35,male,163,...,0.725765,0.7,-288.124487,NaN,NaN,NaN,NaN,0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
730995,659,2025-12-31,2025-12-29,1,manager,onsite,intermediate,41,female,160,...,0.615700,0.6,89.570451,5.714286,4.571429,1.253566,-0.285714,0,0.0,0.0
730996,658,2025-12-31,2025-12-29,1,operations,onsite,intermediate,62,female,170,...,0.727399,0.3,330.564979,5.571429,5.000000,1.511858,0.428571,0,-0.0,0.0
730997,657,2025-12-31,2025-12-29,1,manager,onsite,morning,34,male,182,...,0.747608,0.3,323.777018,6.571429,3.857143,1.272418,-0.285714,0,0.0,0.0
730998,670,2025-12-31,2025-12-29,1,operations,onsite,intermediate,55,male,166,...,0.813008,0.4,113.766074,5.000000,4.857143,2.309401,0.428571,0,-0.0,0.0
730999,1000,2025-12-31,2025-12-29,1,manager,onsite,intermediate,58,female,168,...,0.600601,0.6,-189.028728,6.428571,5.142857,1.618347,-0.285714,0,0.0,0.0

In [27]:
merged = merged.replace([np.inf, -np.inf], np.nan)
merged.fillna(0, inplace=True)

C:\Users\bhanu\AppData\Local\Temp\ipykernel_36212\2871881667.py:2: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '0' has dtype incompatible with datetime64[ns], please explicitly cast to a compatible dtype first.
  merged.fillna(0, inplace=True)

In [28]:
merged.to_csv("../data/processed/merged_features.csv", index=False)
print(f"Feature-engineered dataset saved. Shape: {merged.shape}")

Feature-engineered dataset saved. Shape: (731000, 85)